version: 1.0.2-{build}
image: Visual Studio 2017
configuration: Release

branches:
    only:
      - master

before_build:
  - nuget restore Telegram.Bot.Advanced.sln

build:
  project: Telegram.Bot.Advanced.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: normal

nuget:
  disable_publish_on_pr: true

deploy:
  provider: NuGet
  api_key:
    secure: NgKnkZVr9GZkBrpmRvQpAxbH9AJa1o2EwD+iBBjw/FjJjf8gq+QEo/QWkJ5xJFxj
  skip_symbols: false