image: Visual Studio 2017

branches:
  only:
    - master
    - develop

before_build:
  - nuget restore Telegram.Bot.Advanced.sln

build:
  project: Telegram.Bot.Advanced.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: normal

nuget:
  disable_publish_on_pr: true

deploy:
  - provider: NuGet
    api_key:
      secure: NgKnkZVr9GZkBrpmRvQpAxbH9AJa1o2EwD+iBBjw/FjJjf8gq+QEo/QWkJ5xJFxj
    skip_symbols: false
    on:
      branch: master
  - provider: NuGet
    server: https://ci.appveyor.com/nuget/fuji97-o6dbs344hoht/api/v2/package
    symbol_server: https://ci.appveyor.com/nuget/fuji97-o6dbs344hoht/api/v2/package
    api_key:
      secure: 85RmFvsGyCrOxDNTVLEEHP9z43fXZ8OV7XEinYCHbGA=
    skip_symbols: false
    on:
      branch: develop

for:

  -
    branches:
      only:
        - master

    version: 1.0.5
    configuration: Release

  -
    branches:
      only:
        - develop

    version: 1.0.5.{build}
    configuration: Debug
    dotnet_csproj:
      patch: true
      file: 'Telegram.Bot.Advanced\*.csproj'
      version: '{version}'
      package_version: '{version}'
      assembly_version: '{version}'
      file_version: '{version}'
      informational_version: '{version}'