image: Visual Studio 2019

branches:
  only:
    - master
    - develop

before_build:
  - nuget restore Telegram.Bot.Advanced.sln

build:
  project: Telegram.Bot.Advanced.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: normal

nuget:
  disable_publish_on_pr: true
  
dotnet_csproj:
  patch: true
  file: 'Telegram.Bot.Advanced\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

deploy:
  - provider: NuGet
    api_key:
      secure: 8fnuL50ngB851sG5YoeFE+qYqPQQwFIgGymTX124nDd9mKHyNuT3wSdprueIR3FT
    skip_symbols: false
    on:
      branch: master
  - provider: NuGet
    server: https://ci.appveyor.com/nuget/fuji97/api/v2/package
    symbol_server: https://ci.appveyor.com/nuget/fuji97/api/v2/package
    api_key:
      secure: 85RmFvsGyCrOxDNTVLEEHP9z43fXZ8OV7XEinYCHbGA=
    skip_symbols: false
    on:
      branch: develop

for:

  -
    branches:
      only:
        - master

    version: 3.1.1.2
    configuration: Release

  -
    branches:
      only:
        - develop

    version: 3.1.2.{build}
    configuration: Debug